### PR TITLE
Implement log axis

### PR DESCRIPTION
**Pull request by trvrb**
I've implemented a simple transition to go from linear -> log and back on the y-axis.  I also swapped the lines for circles per #18.  Please revert or add lines if you don't like this.

Also, the buttons need some styling.

### CODE REVIEW

**Comment by trvrb** [comment]
Fit to exponential growth model now implemented. Fixes #7.

**Comment by trvrb** [comment]
It looks like you'd get some improvement to the fit by fitting only to cases/deaths after mid-May.  Looks to be different slopes on either side of this.

**Comment by colinmegill** [comment]
This is fantastic, @trvrb - we'll get the buttons styled. Before we push this, I'd like to de duplicate the data set now - this was less important when it was a line but we don't need multiple points where the data wasn't updated for 5 days. I will create an issue and take care of removing those in the scraping pipeline, retaining the first date that we had those datapoints.

**Comment by trvrb** [comment]
Awesome!  I completely agree with the de duplication.

**Comment by colinmegill** [comment]
@trvrb de duplication now deployed to prod with modified styles and buttons - see what you think

**Comment by trvrb** [comment]
Looks great.  I like it.

**Pull request merged**
